template: native
provider: garage
major-version: 0
providerDefaultBranch: main
publishRegistry: false
providerVersion: github.com/axnic/pulumi-garage/provider.Version
parallel: 3
sdkModuleDir: sdk/go/pulumi-garage
esc:
  enabled: false
