# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .bucket import *
from .bucket_key_permission import *
from .key import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_garage.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_garage.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "garage",
  "mod": "index",
  "fqn": "pulumi_garage",
  "classes": {
   "garage:index:Bucket": "Bucket",
   "garage:index:BucketKeyPermission": "BucketKeyPermission",
   "garage:index:Key": "Key"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "garage",
  "token": "pulumi:providers:garage",
  "fqn": "pulumi_garage",
  "class": "Provider"
 }
]
"""
)
