# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'LifecycleRuleArgsArgs',
    'LifecycleRuleArgsArgsDict',
    'PermissionsArgsArgs',
    'PermissionsArgsArgsDict',
    'QuotasArgsArgs',
    'QuotasArgsArgsDict',
    'WebsiteArgsArgs',
    'WebsiteArgsArgsDict',
]

MYPY = False

if not MYPY:
    class LifecycleRuleArgsArgsDict(TypedDict):
        enabled: pulumi.Input[_builtins.bool]
        """
        Whether this rule is active.
        """
        id: pulumi.Input[_builtins.str]
        """
        A unique identifier for this rule within the bucket.
        """
        abort_incomplete_multipart_upload_days: NotRequired[pulumi.Input[_builtins.int]]
        """
        Abort incomplete multipart uploads this many days after they were initiated. Omit to not clean these up automatically.
        """
        expiration_days: NotRequired[pulumi.Input[_builtins.int]]
        """
        Delete objects this many days after creation. Omit to not expire objects by age.
        """
        prefix: NotRequired[pulumi.Input[_builtins.str]]
        """
        Only objects whose key starts with this prefix are affected. Omit to match every object in the bucket.
        """
elif False:
    LifecycleRuleArgsArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class LifecycleRuleArgsArgs:
    def __init__(__self__, *,
                 enabled: pulumi.Input[_builtins.bool],
                 id: pulumi.Input[_builtins.str],
                 abort_incomplete_multipart_upload_days: Optional[pulumi.Input[_builtins.int]] = None,
                 expiration_days: Optional[pulumi.Input[_builtins.int]] = None,
                 prefix: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.bool] enabled: Whether this rule is active.
        :param pulumi.Input[_builtins.str] id: A unique identifier for this rule within the bucket.
        :param pulumi.Input[_builtins.int] abort_incomplete_multipart_upload_days: Abort incomplete multipart uploads this many days after they were initiated. Omit to not clean these up automatically.
        :param pulumi.Input[_builtins.int] expiration_days: Delete objects this many days after creation. Omit to not expire objects by age.
        :param pulumi.Input[_builtins.str] prefix: Only objects whose key starts with this prefix are affected. Omit to match every object in the bucket.
        """
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "id", id)
        if abort_incomplete_multipart_upload_days is not None:
            pulumi.set(__self__, "abort_incomplete_multipart_upload_days", abort_incomplete_multipart_upload_days)
        if expiration_days is not None:
            pulumi.set(__self__, "expiration_days", expiration_days)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[_builtins.bool]:
        """
        Whether this rule is active.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> pulumi.Input[_builtins.str]:
        """
        A unique identifier for this rule within the bucket.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter(name="abortIncompleteMultipartUploadDays")
    def abort_incomplete_multipart_upload_days(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Abort incomplete multipart uploads this many days after they were initiated. Omit to not clean these up automatically.
        """
        return pulumi.get(self, "abort_incomplete_multipart_upload_days")

    @abort_incomplete_multipart_upload_days.setter
    def abort_incomplete_multipart_upload_days(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "abort_incomplete_multipart_upload_days", value)

    @_builtins.property
    @pulumi.getter(name="expirationDays")
    def expiration_days(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Delete objects this many days after creation. Omit to not expire objects by age.
        """
        return pulumi.get(self, "expiration_days")

    @expiration_days.setter
    def expiration_days(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "expiration_days", value)

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Only objects whose key starts with this prefix are affected. Omit to match every object in the bucket.
        """
        return pulumi.get(self, "prefix")

    @prefix.setter
    def prefix(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "prefix", value)


if not MYPY:
    class PermissionsArgsArgsDict(TypedDict):
        owner: NotRequired[pulumi.Input[_builtins.bool]]
        """
        Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
        """
        read: NotRequired[pulumi.Input[_builtins.bool]]
        """
        Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
        """
        write: NotRequired[pulumi.Input[_builtins.bool]]
        """
        Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
        """
elif False:
    PermissionsArgsArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class PermissionsArgsArgs:
    def __init__(__self__, *,
                 owner: Optional[pulumi.Input[_builtins.bool]] = None,
                 read: Optional[pulumi.Input[_builtins.bool]] = None,
                 write: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.bool] owner: Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
        :param pulumi.Input[_builtins.bool] read: Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
        :param pulumi.Input[_builtins.bool] write: Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
        """
        if owner is not None:
            pulumi.set(__self__, "owner", owner)
        if read is not None:
            pulumi.set(__self__, "read", read)
        if write is not None:
            pulumi.set(__self__, "write", write)

    @_builtins.property
    @pulumi.getter
    def owner(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
        """
        return pulumi.get(self, "owner")

    @owner.setter
    def owner(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "owner", value)

    @_builtins.property
    @pulumi.getter
    def read(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
        """
        return pulumi.get(self, "read")

    @read.setter
    def read(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "read", value)

    @_builtins.property
    @pulumi.getter
    def write(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
        """
        return pulumi.get(self, "write")

    @write.setter
    def write(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "write", value)


if not MYPY:
    class QuotasArgsArgsDict(TypedDict):
        max_objects: NotRequired[pulumi.Input[_builtins.int]]
        """
        The maximum number of objects the bucket may hold. Unset means no limit.
        """
        max_size: NotRequired[pulumi.Input[_builtins.int]]
        """
        The maximum total size, in bytes, the bucket may hold. Unset means no limit.
        """
elif False:
    QuotasArgsArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class QuotasArgsArgs:
    def __init__(__self__, *,
                 max_objects: Optional[pulumi.Input[_builtins.int]] = None,
                 max_size: Optional[pulumi.Input[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.int] max_objects: The maximum number of objects the bucket may hold. Unset means no limit.
        :param pulumi.Input[_builtins.int] max_size: The maximum total size, in bytes, the bucket may hold. Unset means no limit.
        """
        if max_objects is not None:
            pulumi.set(__self__, "max_objects", max_objects)
        if max_size is not None:
            pulumi.set(__self__, "max_size", max_size)

    @_builtins.property
    @pulumi.getter(name="maxObjects")
    def max_objects(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The maximum number of objects the bucket may hold. Unset means no limit.
        """
        return pulumi.get(self, "max_objects")

    @max_objects.setter
    def max_objects(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "max_objects", value)

    @_builtins.property
    @pulumi.getter(name="maxSize")
    def max_size(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The maximum total size, in bytes, the bucket may hold. Unset means no limit.
        """
        return pulumi.get(self, "max_size")

    @max_size.setter
    def max_size(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "max_size", value)


if not MYPY:
    class WebsiteArgsArgsDict(TypedDict):
        index_document: pulumi.Input[_builtins.str]
        """
        The document served for requests to the bucket root or any "directory".
        """
        error_document: NotRequired[pulumi.Input[_builtins.str]]
        """
        The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
        """
elif False:
    WebsiteArgsArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class WebsiteArgsArgs:
    def __init__(__self__, *,
                 index_document: pulumi.Input[_builtins.str],
                 error_document: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] index_document: The document served for requests to the bucket root or any "directory".
        :param pulumi.Input[_builtins.str] error_document: The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
        """
        pulumi.set(__self__, "index_document", index_document)
        if error_document is not None:
            pulumi.set(__self__, "error_document", error_document)

    @_builtins.property
    @pulumi.getter(name="indexDocument")
    def index_document(self) -> pulumi.Input[_builtins.str]:
        """
        The document served for requests to the bucket root or any "directory".
        """
        return pulumi.get(self, "index_document")

    @index_document.setter
    def index_document(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "index_document", value)

    @_builtins.property
    @pulumi.getter(name="errorDocument")
    def error_document(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
        """
        return pulumi.get(self, "error_document")

    @error_document.setter
    def error_document(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "error_document", value)


