# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['BucketKeyPermissionArgs', 'BucketKeyPermission']

@pulumi.input_type
class BucketKeyPermissionArgs:
    def __init__(__self__, *,
                 access_key_id: pulumi.Input[_builtins.str],
                 bucket_id: pulumi.Input[_builtins.str],
                 permissions: pulumi.Input['PermissionsArgsArgs']):
        """
        The set of arguments for constructing a BucketKeyPermission resource.
        :param pulumi.Input[_builtins.str] access_key_id: The access key ID of the Key to grant permissions to.
        :param pulumi.Input[_builtins.str] bucket_id: The ID of the Bucket to grant permissions on.
        :param pulumi.Input['PermissionsArgsArgs'] permissions: The read/write/owner permissions to grant.
        """
        pulumi.set(__self__, "access_key_id", access_key_id)
        pulumi.set(__self__, "bucket_id", bucket_id)
        pulumi.set(__self__, "permissions", permissions)

    @_builtins.property
    @pulumi.getter(name="accessKeyId")
    def access_key_id(self) -> pulumi.Input[_builtins.str]:
        """
        The access key ID of the Key to grant permissions to.
        """
        return pulumi.get(self, "access_key_id")

    @access_key_id.setter
    def access_key_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "access_key_id", value)

    @_builtins.property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the Bucket to grant permissions on.
        """
        return pulumi.get(self, "bucket_id")

    @bucket_id.setter
    def bucket_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "bucket_id", value)

    @_builtins.property
    @pulumi.getter
    def permissions(self) -> pulumi.Input['PermissionsArgsArgs']:
        """
        The read/write/owner permissions to grant.
        """
        return pulumi.get(self, "permissions")

    @permissions.setter
    def permissions(self, value: pulumi.Input['PermissionsArgsArgs']):
        pulumi.set(self, "permissions", value)


@pulumi.type_token("garage:index:BucketKeyPermission")
class BucketKeyPermission(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 permissions: Optional[pulumi.Input[Union['PermissionsArgsArgs', 'PermissionsArgsArgsDict']]] = None,
                 __props__=None):
        """
        Create a BucketKeyPermission resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] access_key_id: The access key ID of the Key to grant permissions to.
        :param pulumi.Input[_builtins.str] bucket_id: The ID of the Bucket to grant permissions on.
        :param pulumi.Input[Union['PermissionsArgsArgs', 'PermissionsArgsArgsDict']] permissions: The read/write/owner permissions to grant.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: BucketKeyPermissionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a BucketKeyPermission resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param BucketKeyPermissionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(BucketKeyPermissionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 bucket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 permissions: Optional[pulumi.Input[Union['PermissionsArgsArgs', 'PermissionsArgsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = BucketKeyPermissionArgs.__new__(BucketKeyPermissionArgs)

            if access_key_id is None and not opts.urn:
                raise TypeError("Missing required property 'access_key_id'")
            __props__.__dict__["access_key_id"] = access_key_id
            if bucket_id is None and not opts.urn:
                raise TypeError("Missing required property 'bucket_id'")
            __props__.__dict__["bucket_id"] = bucket_id
            if permissions is None and not opts.urn:
                raise TypeError("Missing required property 'permissions'")
            __props__.__dict__["permissions"] = permissions
        super(BucketKeyPermission, __self__).__init__(
            'garage:index:BucketKeyPermission',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'BucketKeyPermission':
        """
        Get an existing BucketKeyPermission resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = BucketKeyPermissionArgs.__new__(BucketKeyPermissionArgs)

        __props__.__dict__["access_key_id"] = None
        __props__.__dict__["bucket_id"] = None
        __props__.__dict__["permissions"] = None
        return BucketKeyPermission(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accessKeyId")
    def access_key_id(self) -> pulumi.Output[_builtins.str]:
        """
        The access key ID of the Key to grant permissions to.
        """
        return pulumi.get(self, "access_key_id")

    @_builtins.property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the Bucket to grant permissions on.
        """
        return pulumi.get(self, "bucket_id")

    @_builtins.property
    @pulumi.getter
    def permissions(self) -> pulumi.Output['outputs.PermissionsArgs']:
        """
        The read/write/owner permissions to grant.
        """
        return pulumi.get(self, "permissions")

