# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['BucketArgs', 'Bucket']

@pulumi.input_type
class BucketArgs:
    def __init__(__self__, *,
                 global_alias: Optional[pulumi.Input[_builtins.str]] = None,
                 quotas: Optional[pulumi.Input['QuotasArgsArgs']] = None,
                 website: Optional[pulumi.Input['WebsiteArgsArgs']] = None):
        """
        The set of arguments for constructing a Bucket resource.
        :param pulumi.Input[_builtins.str] global_alias: The bucket's human-readable global alias, e.g. "my-app-data". Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
        :param pulumi.Input['QuotasArgsArgs'] quotas: Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
        :param pulumi.Input['WebsiteArgsArgs'] website: Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
        """
        if global_alias is not None:
            pulumi.set(__self__, "global_alias", global_alias)
        if quotas is not None:
            pulumi.set(__self__, "quotas", quotas)
        if website is not None:
            pulumi.set(__self__, "website", website)

    @_builtins.property
    @pulumi.getter(name="globalAlias")
    def global_alias(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The bucket's human-readable global alias, e.g. "my-app-data". Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
        """
        return pulumi.get(self, "global_alias")

    @global_alias.setter
    def global_alias(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "global_alias", value)

    @_builtins.property
    @pulumi.getter
    def quotas(self) -> Optional[pulumi.Input['QuotasArgsArgs']]:
        """
        Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
        """
        return pulumi.get(self, "quotas")

    @quotas.setter
    def quotas(self, value: Optional[pulumi.Input['QuotasArgsArgs']]):
        pulumi.set(self, "quotas", value)

    @_builtins.property
    @pulumi.getter
    def website(self) -> Optional[pulumi.Input['WebsiteArgsArgs']]:
        """
        Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
        """
        return pulumi.get(self, "website")

    @website.setter
    def website(self, value: Optional[pulumi.Input['WebsiteArgsArgs']]):
        pulumi.set(self, "website", value)


@pulumi.type_token("garage:index:Bucket")
class Bucket(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 global_alias: Optional[pulumi.Input[_builtins.str]] = None,
                 quotas: Optional[pulumi.Input[Union['QuotasArgsArgs', 'QuotasArgsArgsDict']]] = None,
                 website: Optional[pulumi.Input[Union['WebsiteArgsArgs', 'WebsiteArgsArgsDict']]] = None,
                 __props__=None):
        """
        Create a Bucket resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] global_alias: The bucket's human-readable global alias, e.g. "my-app-data". Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
        :param pulumi.Input[Union['QuotasArgsArgs', 'QuotasArgsArgsDict']] quotas: Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
        :param pulumi.Input[Union['WebsiteArgsArgs', 'WebsiteArgsArgsDict']] website: Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[BucketArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Bucket resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param BucketArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(BucketArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 global_alias: Optional[pulumi.Input[_builtins.str]] = None,
                 quotas: Optional[pulumi.Input[Union['QuotasArgsArgs', 'QuotasArgsArgsDict']]] = None,
                 website: Optional[pulumi.Input[Union['WebsiteArgsArgs', 'WebsiteArgsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = BucketArgs.__new__(BucketArgs)

            __props__.__dict__["global_alias"] = global_alias
            __props__.__dict__["quotas"] = quotas
            __props__.__dict__["website"] = website
            __props__.__dict__["bytes"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["objects"] = None
        super(Bucket, __self__).__init__(
            'garage:index:Bucket',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Bucket':
        """
        Get an existing Bucket resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = BucketArgs.__new__(BucketArgs)

        __props__.__dict__["bytes"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["global_alias"] = None
        __props__.__dict__["objects"] = None
        __props__.__dict__["quotas"] = None
        __props__.__dict__["website"] = None
        return Bucket(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def bytes(self) -> pulumi.Output[_builtins.int]:
        """
        The total size, in bytes, of all objects currently stored in the bucket.
        """
        return pulumi.get(self, "bytes")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        The RFC 3339 timestamp at which the bucket was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="globalAlias")
    def global_alias(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The bucket's human-readable global alias, e.g. "my-app-data". Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
        """
        return pulumi.get(self, "global_alias")

    @_builtins.property
    @pulumi.getter
    def objects(self) -> pulumi.Output[_builtins.int]:
        """
        The number of objects currently stored in the bucket.
        """
        return pulumi.get(self, "objects")

    @_builtins.property
    @pulumi.getter
    def quotas(self) -> pulumi.Output[Optional['outputs.QuotasArgs']]:
        """
        Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
        """
        return pulumi.get(self, "quotas")

    @_builtins.property
    @pulumi.getter
    def website(self) -> pulumi.Output[Optional['outputs.WebsiteArgs']]:
        """
        Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
        """
        return pulumi.get(self, "website")

