# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'PermissionsArgs',
    'QuotasArgs',
    'WebsiteArgs',
]

@pulumi.output_type
class PermissionsArgs(dict):
    def __init__(__self__, *,
                 owner: Optional[_builtins.bool] = None,
                 read: Optional[_builtins.bool] = None,
                 write: Optional[_builtins.bool] = None):
        """
        :param _builtins.bool owner: Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
        :param _builtins.bool read: Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
        :param _builtins.bool write: Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
        """
        if owner is not None:
            pulumi.set(__self__, "owner", owner)
        if read is not None:
            pulumi.set(__self__, "read", read)
        if write is not None:
            pulumi.set(__self__, "write", write)

    @_builtins.property
    @pulumi.getter
    def owner(self) -> Optional[_builtins.bool]:
        """
        Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
        """
        return pulumi.get(self, "owner")

    @_builtins.property
    @pulumi.getter
    def read(self) -> Optional[_builtins.bool]:
        """
        Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
        """
        return pulumi.get(self, "read")

    @_builtins.property
    @pulumi.getter
    def write(self) -> Optional[_builtins.bool]:
        """
        Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
        """
        return pulumi.get(self, "write")


@pulumi.output_type
class QuotasArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "maxObjects":
            suggest = "max_objects"
        elif key == "maxSize":
            suggest = "max_size"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in QuotasArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        QuotasArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        QuotasArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 max_objects: Optional[_builtins.int] = None,
                 max_size: Optional[_builtins.int] = None):
        """
        :param _builtins.int max_objects: The maximum number of objects the bucket may hold. Unset means no limit.
        :param _builtins.int max_size: The maximum total size, in bytes, the bucket may hold. Unset means no limit.
        """
        if max_objects is not None:
            pulumi.set(__self__, "max_objects", max_objects)
        if max_size is not None:
            pulumi.set(__self__, "max_size", max_size)

    @_builtins.property
    @pulumi.getter(name="maxObjects")
    def max_objects(self) -> Optional[_builtins.int]:
        """
        The maximum number of objects the bucket may hold. Unset means no limit.
        """
        return pulumi.get(self, "max_objects")

    @_builtins.property
    @pulumi.getter(name="maxSize")
    def max_size(self) -> Optional[_builtins.int]:
        """
        The maximum total size, in bytes, the bucket may hold. Unset means no limit.
        """
        return pulumi.get(self, "max_size")


@pulumi.output_type
class WebsiteArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "indexDocument":
            suggest = "index_document"
        elif key == "errorDocument":
            suggest = "error_document"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in WebsiteArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        WebsiteArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        WebsiteArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 index_document: _builtins.str,
                 error_document: Optional[_builtins.str] = None):
        """
        :param _builtins.str index_document: The document served for requests to the bucket root or any "directory".
        :param _builtins.str error_document: The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
        """
        pulumi.set(__self__, "index_document", index_document)
        if error_document is not None:
            pulumi.set(__self__, "error_document", error_document)

    @_builtins.property
    @pulumi.getter(name="indexDocument")
    def index_document(self) -> _builtins.str:
        """
        The document served for requests to the bucket root or any "directory".
        """
        return pulumi.get(self, "index_document")

    @_builtins.property
    @pulumi.getter(name="errorDocument")
    def error_document(self) -> Optional[_builtins.str]:
        """
        The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
        """
        return pulumi.get(self, "error_document")


