// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.Garage.Outputs
{

    [OutputType]
    public sealed class LifecycleRuleArgs
    {
        /// <summary>
        /// Abort incomplete multipart uploads this many days after they were initiated. Omit to not clean these up automatically.
        /// </summary>
        public readonly int? AbortIncompleteMultipartUploadDays;
        /// <summary>
        /// Whether this rule is active.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Delete objects this many days after creation. Omit to not expire objects by age.
        /// </summary>
        public readonly int? ExpirationDays;
        /// <summary>
        /// A unique identifier for this rule within the bucket.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Only objects whose key starts with this prefix are affected. Omit to match every object in the bucket.
        /// </summary>
        public readonly string? Prefix;

        [OutputConstructor]
        private LifecycleRuleArgs(
            int? abortIncompleteMultipartUploadDays,

            bool enabled,

            int? expirationDays,

            string id,

            string? prefix)
        {
            AbortIncompleteMultipartUploadDays = abortIncompleteMultipartUploadDays;
            Enabled = enabled;
            ExpirationDays = expirationDays;
            Id = id;
            Prefix = prefix;
        }
    }
}
