// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.Garage.Outputs
{

    [OutputType]
    public sealed class QuotasArgs
    {
        /// <summary>
        /// The maximum number of objects the bucket may hold. Unset means no limit.
        /// </summary>
        public readonly int? MaxObjects;
        /// <summary>
        /// The maximum total size, in bytes, the bucket may hold. Unset means no limit.
        /// </summary>
        public readonly int? MaxSize;

        [OutputConstructor]
        private QuotasArgs(
            int? maxObjects,

            int? maxSize)
        {
            MaxObjects = maxObjects;
            MaxSize = maxSize;
        }
    }
}
