// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.Garage.Outputs
{

    [OutputType]
    public sealed class WebsiteArgs
    {
        /// <summary>
        /// The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
        /// </summary>
        public readonly string? ErrorDocument;
        /// <summary>
        /// The document served for requests to the bucket root or any "directory".
        /// </summary>
        public readonly string IndexDocument;

        [OutputConstructor]
        private WebsiteArgs(
            string? errorDocument,

            string indexDocument)
        {
            ErrorDocument = errorDocument;
            IndexDocument = indexDocument;
        }
    }
}
