// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage;

import com.axnic.pulumi.garage.BucketArgs;
import com.axnic.pulumi.garage.Utilities;
import com.axnic.pulumi.garage.outputs.QuotasArgs;
import com.axnic.pulumi.garage.outputs.WebsiteArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="garage:index:Bucket")
public class Bucket extends com.pulumi.resources.CustomResource {
    /**
     * The total size, in bytes, of all objects currently stored in the bucket.
     * 
     */
    @Export(name="bytes", refs={Integer.class}, tree="[0]")
    private Output<Integer> bytes;

    /**
     * @return The total size, in bytes, of all objects currently stored in the bucket.
     * 
     */
    public Output<Integer> bytes() {
        return this.bytes;
    }
    /**
     * The RFC 3339 timestamp at which the bucket was created.
     * 
     */
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    /**
     * @return The RFC 3339 timestamp at which the bucket was created.
     * 
     */
    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * The bucket&#39;s human-readable global alias, e.g. &#34;my-app-data&#34;. Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
     * 
     */
    @Export(name="globalAlias", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> globalAlias;

    /**
     * @return The bucket&#39;s human-readable global alias, e.g. &#34;my-app-data&#34;. Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
     * 
     */
    public Output<Optional<String>> globalAlias() {
        return Codegen.optional(this.globalAlias);
    }
    /**
     * The number of objects currently stored in the bucket.
     * 
     */
    @Export(name="objects", refs={Integer.class}, tree="[0]")
    private Output<Integer> objects;

    /**
     * @return The number of objects currently stored in the bucket.
     * 
     */
    public Output<Integer> objects() {
        return this.objects;
    }
    /**
     * Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
     * 
     */
    @Export(name="quotas", refs={QuotasArgs.class}, tree="[0]")
    private Output</* @Nullable */ QuotasArgs> quotas;

    /**
     * @return Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
     * 
     */
    public Output<Optional<QuotasArgs>> quotas() {
        return Codegen.optional(this.quotas);
    }
    /**
     * Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
     * 
     */
    @Export(name="website", refs={WebsiteArgs.class}, tree="[0]")
    private Output</* @Nullable */ WebsiteArgs> website;

    /**
     * @return Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
     * 
     */
    public Output<Optional<WebsiteArgs>> website() {
        return Codegen.optional(this.website);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Bucket(java.lang.String name) {
        this(name, BucketArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Bucket(java.lang.String name, @Nullable BucketArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Bucket(java.lang.String name, @Nullable BucketArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("garage:index:Bucket", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Bucket(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("garage:index:Bucket", name, null, makeResourceOptions(options, id), false);
    }

    private static BucketArgs makeArgs(@Nullable BucketArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? BucketArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/axnic/pulumi-garage")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Bucket get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Bucket(name, id, options);
    }
}
