// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage;

import com.axnic.pulumi.garage.BucketKeyPermissionArgs;
import com.axnic.pulumi.garage.Utilities;
import com.axnic.pulumi.garage.outputs.PermissionsArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import javax.annotation.Nullable;

@ResourceType(type="garage:index:BucketKeyPermission")
public class BucketKeyPermission extends com.pulumi.resources.CustomResource {
    /**
     * The access key ID of the Key to grant permissions to.
     * 
     */
    @Export(name="accessKeyId", refs={String.class}, tree="[0]")
    private Output<String> accessKeyId;

    /**
     * @return The access key ID of the Key to grant permissions to.
     * 
     */
    public Output<String> accessKeyId() {
        return this.accessKeyId;
    }
    /**
     * The ID of the Bucket to grant permissions on.
     * 
     */
    @Export(name="bucketId", refs={String.class}, tree="[0]")
    private Output<String> bucketId;

    /**
     * @return The ID of the Bucket to grant permissions on.
     * 
     */
    public Output<String> bucketId() {
        return this.bucketId;
    }
    /**
     * The read/write/owner permissions to grant.
     * 
     */
    @Export(name="permissions", refs={PermissionsArgs.class}, tree="[0]")
    private Output<PermissionsArgs> permissions;

    /**
     * @return The read/write/owner permissions to grant.
     * 
     */
    public Output<PermissionsArgs> permissions() {
        return this.permissions;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public BucketKeyPermission(java.lang.String name) {
        this(name, BucketKeyPermissionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public BucketKeyPermission(java.lang.String name, BucketKeyPermissionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public BucketKeyPermission(java.lang.String name, BucketKeyPermissionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("garage:index:BucketKeyPermission", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private BucketKeyPermission(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("garage:index:BucketKeyPermission", name, null, makeResourceOptions(options, id), false);
    }

    private static BucketKeyPermissionArgs makeArgs(BucketKeyPermissionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? BucketKeyPermissionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/axnic/pulumi-garage")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static BucketKeyPermission get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new BucketKeyPermission(name, id, options);
    }
}
