// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage;

import com.axnic.pulumi.garage.inputs.QuotasArgsArgs;
import com.axnic.pulumi.garage.inputs.WebsiteArgsArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BucketArgs extends com.pulumi.resources.ResourceArgs {

    public static final BucketArgs Empty = new BucketArgs();

    /**
     * The bucket&#39;s human-readable global alias, e.g. &#34;my-app-data&#34;. Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
     * 
     */
    @Import(name="globalAlias")
    private @Nullable Output<String> globalAlias;

    /**
     * @return The bucket&#39;s human-readable global alias, e.g. &#34;my-app-data&#34;. Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
     * 
     */
    public Optional<Output<String>> globalAlias() {
        return Optional.ofNullable(this.globalAlias);
    }

    /**
     * Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
     * 
     */
    @Import(name="quotas")
    private @Nullable Output<QuotasArgsArgs> quotas;

    /**
     * @return Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
     * 
     */
    public Optional<Output<QuotasArgsArgs>> quotas() {
        return Optional.ofNullable(this.quotas);
    }

    /**
     * Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
     * 
     */
    @Import(name="website")
    private @Nullable Output<WebsiteArgsArgs> website;

    /**
     * @return Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
     * 
     */
    public Optional<Output<WebsiteArgsArgs>> website() {
        return Optional.ofNullable(this.website);
    }

    private BucketArgs() {}

    private BucketArgs(BucketArgs $) {
        this.globalAlias = $.globalAlias;
        this.quotas = $.quotas;
        this.website = $.website;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BucketArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BucketArgs $;

        public Builder() {
            $ = new BucketArgs();
        }

        public Builder(BucketArgs defaults) {
            $ = new BucketArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param globalAlias The bucket&#39;s human-readable global alias, e.g. &#34;my-app-data&#34;. Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
         * 
         * @return builder
         * 
         */
        public Builder globalAlias(@Nullable Output<String> globalAlias) {
            $.globalAlias = globalAlias;
            return this;
        }

        /**
         * @param globalAlias The bucket&#39;s human-readable global alias, e.g. &#34;my-app-data&#34;. Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
         * 
         * @return builder
         * 
         */
        public Builder globalAlias(String globalAlias) {
            return globalAlias(Output.of(globalAlias));
        }

        /**
         * @param quotas Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
         * 
         * @return builder
         * 
         */
        public Builder quotas(@Nullable Output<QuotasArgsArgs> quotas) {
            $.quotas = quotas;
            return this;
        }

        /**
         * @param quotas Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
         * 
         * @return builder
         * 
         */
        public Builder quotas(QuotasArgsArgs quotas) {
            return quotas(Output.of(quotas));
        }

        /**
         * @param website Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
         * 
         * @return builder
         * 
         */
        public Builder website(@Nullable Output<WebsiteArgsArgs> website) {
            $.website = website;
            return this;
        }

        /**
         * @param website Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
         * 
         * @return builder
         * 
         */
        public Builder website(WebsiteArgsArgs website) {
            return website(Output.of(website));
        }

        public BucketArgs build() {
            return $;
        }
    }

}
