// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage;

import com.axnic.pulumi.garage.inputs.PermissionsArgsArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class BucketKeyPermissionArgs extends com.pulumi.resources.ResourceArgs {

    public static final BucketKeyPermissionArgs Empty = new BucketKeyPermissionArgs();

    /**
     * The access key ID of the Key to grant permissions to.
     * 
     */
    @Import(name="accessKeyId", required=true)
    private Output<String> accessKeyId;

    /**
     * @return The access key ID of the Key to grant permissions to.
     * 
     */
    public Output<String> accessKeyId() {
        return this.accessKeyId;
    }

    /**
     * The ID of the Bucket to grant permissions on.
     * 
     */
    @Import(name="bucketId", required=true)
    private Output<String> bucketId;

    /**
     * @return The ID of the Bucket to grant permissions on.
     * 
     */
    public Output<String> bucketId() {
        return this.bucketId;
    }

    /**
     * The read/write/owner permissions to grant.
     * 
     */
    @Import(name="permissions", required=true)
    private Output<PermissionsArgsArgs> permissions;

    /**
     * @return The read/write/owner permissions to grant.
     * 
     */
    public Output<PermissionsArgsArgs> permissions() {
        return this.permissions;
    }

    private BucketKeyPermissionArgs() {}

    private BucketKeyPermissionArgs(BucketKeyPermissionArgs $) {
        this.accessKeyId = $.accessKeyId;
        this.bucketId = $.bucketId;
        this.permissions = $.permissions;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BucketKeyPermissionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BucketKeyPermissionArgs $;

        public Builder() {
            $ = new BucketKeyPermissionArgs();
        }

        public Builder(BucketKeyPermissionArgs defaults) {
            $ = new BucketKeyPermissionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessKeyId The access key ID of the Key to grant permissions to.
         * 
         * @return builder
         * 
         */
        public Builder accessKeyId(Output<String> accessKeyId) {
            $.accessKeyId = accessKeyId;
            return this;
        }

        /**
         * @param accessKeyId The access key ID of the Key to grant permissions to.
         * 
         * @return builder
         * 
         */
        public Builder accessKeyId(String accessKeyId) {
            return accessKeyId(Output.of(accessKeyId));
        }

        /**
         * @param bucketId The ID of the Bucket to grant permissions on.
         * 
         * @return builder
         * 
         */
        public Builder bucketId(Output<String> bucketId) {
            $.bucketId = bucketId;
            return this;
        }

        /**
         * @param bucketId The ID of the Bucket to grant permissions on.
         * 
         * @return builder
         * 
         */
        public Builder bucketId(String bucketId) {
            return bucketId(Output.of(bucketId));
        }

        /**
         * @param permissions The read/write/owner permissions to grant.
         * 
         * @return builder
         * 
         */
        public Builder permissions(Output<PermissionsArgsArgs> permissions) {
            $.permissions = permissions;
            return this;
        }

        /**
         * @param permissions The read/write/owner permissions to grant.
         * 
         * @return builder
         * 
         */
        public Builder permissions(PermissionsArgsArgs permissions) {
            return permissions(Output.of(permissions));
        }

        public BucketKeyPermissionArgs build() {
            if ($.accessKeyId == null) {
                throw new MissingRequiredPropertyException("BucketKeyPermissionArgs", "accessKeyId");
            }
            if ($.bucketId == null) {
                throw new MissingRequiredPropertyException("BucketKeyPermissionArgs", "bucketId");
            }
            if ($.permissions == null) {
                throw new MissingRequiredPropertyException("BucketKeyPermissionArgs", "permissions");
            }
            return $;
        }
    }

}
