// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("garage");
/**
 * A bearer token authorized against the Garage Admin API. Falls back to the GARAGE_ADMIN_TOKEN environment variable if not set.
 * 
 */
    public Optional<String> adminToken() {
        return Codegen.stringProp("adminToken").config(config).get();
    }
/**
 * The base URL of the Garage Admin API, e.g. &#34;http://localhost:3903&#34;. Falls back to the GARAGE_ADMIN_ENDPOINT environment variable if not set.
 * 
 */
    public Optional<String> endpoint() {
        return Codegen.stringProp("endpoint").config(config).get();
    }
}
