// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * A bearer token authorized against the Garage Admin API. Falls back to the GARAGE_ADMIN_TOKEN environment variable if not set.
     * 
     */
    @Import(name="adminToken")
    private @Nullable Output<String> adminToken;

    /**
     * @return A bearer token authorized against the Garage Admin API. Falls back to the GARAGE_ADMIN_TOKEN environment variable if not set.
     * 
     */
    public Optional<Output<String>> adminToken() {
        return Optional.ofNullable(this.adminToken);
    }

    /**
     * The base URL of the Garage Admin API, e.g. &#34;http://localhost:3903&#34;. Falls back to the GARAGE_ADMIN_ENDPOINT environment variable if not set.
     * 
     */
    @Import(name="endpoint")
    private @Nullable Output<String> endpoint;

    /**
     * @return The base URL of the Garage Admin API, e.g. &#34;http://localhost:3903&#34;. Falls back to the GARAGE_ADMIN_ENDPOINT environment variable if not set.
     * 
     */
    public Optional<Output<String>> endpoint() {
        return Optional.ofNullable(this.endpoint);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.adminToken = $.adminToken;
        this.endpoint = $.endpoint;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param adminToken A bearer token authorized against the Garage Admin API. Falls back to the GARAGE_ADMIN_TOKEN environment variable if not set.
         * 
         * @return builder
         * 
         */
        public Builder adminToken(@Nullable Output<String> adminToken) {
            $.adminToken = adminToken;
            return this;
        }

        /**
         * @param adminToken A bearer token authorized against the Garage Admin API. Falls back to the GARAGE_ADMIN_TOKEN environment variable if not set.
         * 
         * @return builder
         * 
         */
        public Builder adminToken(String adminToken) {
            return adminToken(Output.of(adminToken));
        }

        /**
         * @param endpoint The base URL of the Garage Admin API, e.g. &#34;http://localhost:3903&#34;. Falls back to the GARAGE_ADMIN_ENDPOINT environment variable if not set.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(@Nullable Output<String> endpoint) {
            $.endpoint = endpoint;
            return this;
        }

        /**
         * @param endpoint The base URL of the Garage Admin API, e.g. &#34;http://localhost:3903&#34;. Falls back to the GARAGE_ADMIN_ENDPOINT environment variable if not set.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(String endpoint) {
            return endpoint(Output.of(endpoint));
        }

        public ProviderArgs build() {
            return $;
        }
    }

}
