// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumigarage

import (
	"context"
	"reflect"

	"errors"
	"github.com/axnic/pulumi-garage/sdk/go/pulumi-garage/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type BucketKeyPermission struct {
	pulumi.CustomResourceState

	// The access key ID of the Key to grant permissions to.
	AccessKeyId pulumi.StringOutput `pulumi:"accessKeyId"`
	// The ID of the Bucket to grant permissions on.
	BucketId pulumi.StringOutput `pulumi:"bucketId"`
	// The read/write/owner permissions to grant.
	Permissions PermissionsArgsOutput `pulumi:"permissions"`
}

// NewBucketKeyPermission registers a new resource with the given unique name, arguments, and options.
func NewBucketKeyPermission(ctx *pulumi.Context,
	name string, args *BucketKeyPermissionArgs, opts ...pulumi.ResourceOption) (*BucketKeyPermission, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccessKeyId == nil {
		return nil, errors.New("invalid value for required argument 'AccessKeyId'")
	}
	if args.BucketId == nil {
		return nil, errors.New("invalid value for required argument 'BucketId'")
	}
	if args.Permissions == nil {
		return nil, errors.New("invalid value for required argument 'Permissions'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource BucketKeyPermission
	err := ctx.RegisterResource("garage:index:BucketKeyPermission", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBucketKeyPermission gets an existing BucketKeyPermission resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBucketKeyPermission(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BucketKeyPermissionState, opts ...pulumi.ResourceOption) (*BucketKeyPermission, error) {
	var resource BucketKeyPermission
	err := ctx.ReadResource("garage:index:BucketKeyPermission", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BucketKeyPermission resources.
type bucketKeyPermissionState struct {
}

type BucketKeyPermissionState struct {
}

func (BucketKeyPermissionState) ElementType() reflect.Type {
	return reflect.TypeOf((*bucketKeyPermissionState)(nil)).Elem()
}

type bucketKeyPermissionArgs struct {
	// The access key ID of the Key to grant permissions to.
	AccessKeyId string `pulumi:"accessKeyId"`
	// The ID of the Bucket to grant permissions on.
	BucketId string `pulumi:"bucketId"`
	// The read/write/owner permissions to grant.
	Permissions PermissionsArgs `pulumi:"permissions"`
}

// The set of arguments for constructing a BucketKeyPermission resource.
type BucketKeyPermissionArgs struct {
	// The access key ID of the Key to grant permissions to.
	AccessKeyId pulumi.StringInput
	// The ID of the Bucket to grant permissions on.
	BucketId pulumi.StringInput
	// The read/write/owner permissions to grant.
	Permissions PermissionsArgsInput
}

func (BucketKeyPermissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*bucketKeyPermissionArgs)(nil)).Elem()
}

type BucketKeyPermissionInput interface {
	pulumi.Input

	ToBucketKeyPermissionOutput() BucketKeyPermissionOutput
	ToBucketKeyPermissionOutputWithContext(ctx context.Context) BucketKeyPermissionOutput
}

func (*BucketKeyPermission) ElementType() reflect.Type {
	return reflect.TypeOf((**BucketKeyPermission)(nil)).Elem()
}

func (i *BucketKeyPermission) ToBucketKeyPermissionOutput() BucketKeyPermissionOutput {
	return i.ToBucketKeyPermissionOutputWithContext(context.Background())
}

func (i *BucketKeyPermission) ToBucketKeyPermissionOutputWithContext(ctx context.Context) BucketKeyPermissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BucketKeyPermissionOutput)
}

// BucketKeyPermissionArrayInput is an input type that accepts BucketKeyPermissionArray and BucketKeyPermissionArrayOutput values.
// You can construct a concrete instance of `BucketKeyPermissionArrayInput` via:
//
//	BucketKeyPermissionArray{ BucketKeyPermissionArgs{...} }
type BucketKeyPermissionArrayInput interface {
	pulumi.Input

	ToBucketKeyPermissionArrayOutput() BucketKeyPermissionArrayOutput
	ToBucketKeyPermissionArrayOutputWithContext(context.Context) BucketKeyPermissionArrayOutput
}

type BucketKeyPermissionArray []BucketKeyPermissionInput

func (BucketKeyPermissionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*BucketKeyPermission)(nil)).Elem()
}

func (i BucketKeyPermissionArray) ToBucketKeyPermissionArrayOutput() BucketKeyPermissionArrayOutput {
	return i.ToBucketKeyPermissionArrayOutputWithContext(context.Background())
}

func (i BucketKeyPermissionArray) ToBucketKeyPermissionArrayOutputWithContext(ctx context.Context) BucketKeyPermissionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BucketKeyPermissionArrayOutput)
}

// BucketKeyPermissionMapInput is an input type that accepts BucketKeyPermissionMap and BucketKeyPermissionMapOutput values.
// You can construct a concrete instance of `BucketKeyPermissionMapInput` via:
//
//	BucketKeyPermissionMap{ "key": BucketKeyPermissionArgs{...} }
type BucketKeyPermissionMapInput interface {
	pulumi.Input

	ToBucketKeyPermissionMapOutput() BucketKeyPermissionMapOutput
	ToBucketKeyPermissionMapOutputWithContext(context.Context) BucketKeyPermissionMapOutput
}

type BucketKeyPermissionMap map[string]BucketKeyPermissionInput

func (BucketKeyPermissionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*BucketKeyPermission)(nil)).Elem()
}

func (i BucketKeyPermissionMap) ToBucketKeyPermissionMapOutput() BucketKeyPermissionMapOutput {
	return i.ToBucketKeyPermissionMapOutputWithContext(context.Background())
}

func (i BucketKeyPermissionMap) ToBucketKeyPermissionMapOutputWithContext(ctx context.Context) BucketKeyPermissionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BucketKeyPermissionMapOutput)
}

type BucketKeyPermissionOutput struct{ *pulumi.OutputState }

func (BucketKeyPermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BucketKeyPermission)(nil)).Elem()
}

func (o BucketKeyPermissionOutput) ToBucketKeyPermissionOutput() BucketKeyPermissionOutput {
	return o
}

func (o BucketKeyPermissionOutput) ToBucketKeyPermissionOutputWithContext(ctx context.Context) BucketKeyPermissionOutput {
	return o
}

// The access key ID of the Key to grant permissions to.
func (o BucketKeyPermissionOutput) AccessKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *BucketKeyPermission) pulumi.StringOutput { return v.AccessKeyId }).(pulumi.StringOutput)
}

// The ID of the Bucket to grant permissions on.
func (o BucketKeyPermissionOutput) BucketId() pulumi.StringOutput {
	return o.ApplyT(func(v *BucketKeyPermission) pulumi.StringOutput { return v.BucketId }).(pulumi.StringOutput)
}

// The read/write/owner permissions to grant.
func (o BucketKeyPermissionOutput) Permissions() PermissionsArgsOutput {
	return o.ApplyT(func(v *BucketKeyPermission) PermissionsArgsOutput { return v.Permissions }).(PermissionsArgsOutput)
}

type BucketKeyPermissionArrayOutput struct{ *pulumi.OutputState }

func (BucketKeyPermissionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*BucketKeyPermission)(nil)).Elem()
}

func (o BucketKeyPermissionArrayOutput) ToBucketKeyPermissionArrayOutput() BucketKeyPermissionArrayOutput {
	return o
}

func (o BucketKeyPermissionArrayOutput) ToBucketKeyPermissionArrayOutputWithContext(ctx context.Context) BucketKeyPermissionArrayOutput {
	return o
}

func (o BucketKeyPermissionArrayOutput) Index(i pulumi.IntInput) BucketKeyPermissionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *BucketKeyPermission {
		return vs[0].([]*BucketKeyPermission)[vs[1].(int)]
	}).(BucketKeyPermissionOutput)
}

type BucketKeyPermissionMapOutput struct{ *pulumi.OutputState }

func (BucketKeyPermissionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*BucketKeyPermission)(nil)).Elem()
}

func (o BucketKeyPermissionMapOutput) ToBucketKeyPermissionMapOutput() BucketKeyPermissionMapOutput {
	return o
}

func (o BucketKeyPermissionMapOutput) ToBucketKeyPermissionMapOutputWithContext(ctx context.Context) BucketKeyPermissionMapOutput {
	return o
}

func (o BucketKeyPermissionMapOutput) MapIndex(k pulumi.StringInput) BucketKeyPermissionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *BucketKeyPermission {
		return vs[0].(map[string]*BucketKeyPermission)[vs[1].(string)]
	}).(BucketKeyPermissionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BucketKeyPermissionInput)(nil)).Elem(), &BucketKeyPermission{})
	pulumi.RegisterInputType(reflect.TypeOf((*BucketKeyPermissionArrayInput)(nil)).Elem(), BucketKeyPermissionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*BucketKeyPermissionMapInput)(nil)).Elem(), BucketKeyPermissionMap{})
	pulumi.RegisterOutputType(BucketKeyPermissionOutput{})
	pulumi.RegisterOutputType(BucketKeyPermissionArrayOutput{})
	pulumi.RegisterOutputType(BucketKeyPermissionMapOutput{})
}
