// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumigarage

import (
	"context"
	"reflect"

	"github.com/axnic/pulumi-garage/sdk/go/pulumi-garage/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type LifecycleRuleArgs struct {
	// Abort incomplete multipart uploads this many days after they were initiated. Omit to not clean these up automatically.
	AbortIncompleteMultipartUploadDays *int `pulumi:"abortIncompleteMultipartUploadDays"`
	// Whether this rule is active.
	Enabled bool `pulumi:"enabled"`
	// Delete objects this many days after creation. Omit to not expire objects by age.
	ExpirationDays *int `pulumi:"expirationDays"`
	// A unique identifier for this rule within the bucket.
	Id string `pulumi:"id"`
	// Only objects whose key starts with this prefix are affected. Omit to match every object in the bucket.
	Prefix *string `pulumi:"prefix"`
}

// LifecycleRuleArgsInput is an input type that accepts LifecycleRuleArgsArgs and LifecycleRuleArgsOutput values.
// You can construct a concrete instance of `LifecycleRuleArgsInput` via:
//
//	LifecycleRuleArgsArgs{...}
type LifecycleRuleArgsInput interface {
	pulumi.Input

	ToLifecycleRuleArgsOutput() LifecycleRuleArgsOutput
	ToLifecycleRuleArgsOutputWithContext(context.Context) LifecycleRuleArgsOutput
}

type LifecycleRuleArgsArgs struct {
	// Abort incomplete multipart uploads this many days after they were initiated. Omit to not clean these up automatically.
	AbortIncompleteMultipartUploadDays pulumi.IntPtrInput `pulumi:"abortIncompleteMultipartUploadDays"`
	// Whether this rule is active.
	Enabled pulumi.BoolInput `pulumi:"enabled"`
	// Delete objects this many days after creation. Omit to not expire objects by age.
	ExpirationDays pulumi.IntPtrInput `pulumi:"expirationDays"`
	// A unique identifier for this rule within the bucket.
	Id pulumi.StringInput `pulumi:"id"`
	// Only objects whose key starts with this prefix are affected. Omit to match every object in the bucket.
	Prefix pulumi.StringPtrInput `pulumi:"prefix"`
}

func (LifecycleRuleArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LifecycleRuleArgs)(nil)).Elem()
}

func (i LifecycleRuleArgsArgs) ToLifecycleRuleArgsOutput() LifecycleRuleArgsOutput {
	return i.ToLifecycleRuleArgsOutputWithContext(context.Background())
}

func (i LifecycleRuleArgsArgs) ToLifecycleRuleArgsOutputWithContext(ctx context.Context) LifecycleRuleArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LifecycleRuleArgsOutput)
}

// LifecycleRuleArgsArrayInput is an input type that accepts LifecycleRuleArgsArray and LifecycleRuleArgsArrayOutput values.
// You can construct a concrete instance of `LifecycleRuleArgsArrayInput` via:
//
//	LifecycleRuleArgsArray{ LifecycleRuleArgsArgs{...} }
type LifecycleRuleArgsArrayInput interface {
	pulumi.Input

	ToLifecycleRuleArgsArrayOutput() LifecycleRuleArgsArrayOutput
	ToLifecycleRuleArgsArrayOutputWithContext(context.Context) LifecycleRuleArgsArrayOutput
}

type LifecycleRuleArgsArray []LifecycleRuleArgsInput

func (LifecycleRuleArgsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]LifecycleRuleArgs)(nil)).Elem()
}

func (i LifecycleRuleArgsArray) ToLifecycleRuleArgsArrayOutput() LifecycleRuleArgsArrayOutput {
	return i.ToLifecycleRuleArgsArrayOutputWithContext(context.Background())
}

func (i LifecycleRuleArgsArray) ToLifecycleRuleArgsArrayOutputWithContext(ctx context.Context) LifecycleRuleArgsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LifecycleRuleArgsArrayOutput)
}

type LifecycleRuleArgsOutput struct{ *pulumi.OutputState }

func (LifecycleRuleArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LifecycleRuleArgs)(nil)).Elem()
}

func (o LifecycleRuleArgsOutput) ToLifecycleRuleArgsOutput() LifecycleRuleArgsOutput {
	return o
}

func (o LifecycleRuleArgsOutput) ToLifecycleRuleArgsOutputWithContext(ctx context.Context) LifecycleRuleArgsOutput {
	return o
}

// Abort incomplete multipart uploads this many days after they were initiated. Omit to not clean these up automatically.
func (o LifecycleRuleArgsOutput) AbortIncompleteMultipartUploadDays() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LifecycleRuleArgs) *int { return v.AbortIncompleteMultipartUploadDays }).(pulumi.IntPtrOutput)
}

// Whether this rule is active.
func (o LifecycleRuleArgsOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LifecycleRuleArgs) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Delete objects this many days after creation. Omit to not expire objects by age.
func (o LifecycleRuleArgsOutput) ExpirationDays() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LifecycleRuleArgs) *int { return v.ExpirationDays }).(pulumi.IntPtrOutput)
}

// A unique identifier for this rule within the bucket.
func (o LifecycleRuleArgsOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LifecycleRuleArgs) string { return v.Id }).(pulumi.StringOutput)
}

// Only objects whose key starts with this prefix are affected. Omit to match every object in the bucket.
func (o LifecycleRuleArgsOutput) Prefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LifecycleRuleArgs) *string { return v.Prefix }).(pulumi.StringPtrOutput)
}

type LifecycleRuleArgsArrayOutput struct{ *pulumi.OutputState }

func (LifecycleRuleArgsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]LifecycleRuleArgs)(nil)).Elem()
}

func (o LifecycleRuleArgsArrayOutput) ToLifecycleRuleArgsArrayOutput() LifecycleRuleArgsArrayOutput {
	return o
}

func (o LifecycleRuleArgsArrayOutput) ToLifecycleRuleArgsArrayOutputWithContext(ctx context.Context) LifecycleRuleArgsArrayOutput {
	return o
}

func (o LifecycleRuleArgsArrayOutput) Index(i pulumi.IntInput) LifecycleRuleArgsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) LifecycleRuleArgs {
		return vs[0].([]LifecycleRuleArgs)[vs[1].(int)]
	}).(LifecycleRuleArgsOutput)
}

type PermissionsArgs struct {
	// Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
	Owner *bool `pulumi:"owner"`
	// Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
	Read *bool `pulumi:"read"`
	// Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
	Write *bool `pulumi:"write"`
}

// PermissionsArgsInput is an input type that accepts PermissionsArgsArgs and PermissionsArgsOutput values.
// You can construct a concrete instance of `PermissionsArgsInput` via:
//
//	PermissionsArgsArgs{...}
type PermissionsArgsInput interface {
	pulumi.Input

	ToPermissionsArgsOutput() PermissionsArgsOutput
	ToPermissionsArgsOutputWithContext(context.Context) PermissionsArgsOutput
}

type PermissionsArgsArgs struct {
	// Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
	Owner pulumi.BoolPtrInput `pulumi:"owner"`
	// Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
	Read pulumi.BoolPtrInput `pulumi:"read"`
	// Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
	Write pulumi.BoolPtrInput `pulumi:"write"`
}

func (PermissionsArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*PermissionsArgs)(nil)).Elem()
}

func (i PermissionsArgsArgs) ToPermissionsArgsOutput() PermissionsArgsOutput {
	return i.ToPermissionsArgsOutputWithContext(context.Background())
}

func (i PermissionsArgsArgs) ToPermissionsArgsOutputWithContext(ctx context.Context) PermissionsArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PermissionsArgsOutput)
}

type PermissionsArgsOutput struct{ *pulumi.OutputState }

func (PermissionsArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PermissionsArgs)(nil)).Elem()
}

func (o PermissionsArgsOutput) ToPermissionsArgsOutput() PermissionsArgsOutput {
	return o
}

func (o PermissionsArgsOutput) ToPermissionsArgsOutputWithContext(ctx context.Context) PermissionsArgsOutput {
	return o
}

// Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
func (o PermissionsArgsOutput) Owner() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v PermissionsArgs) *bool { return v.Owner }).(pulumi.BoolPtrOutput)
}

// Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
func (o PermissionsArgsOutput) Read() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v PermissionsArgs) *bool { return v.Read }).(pulumi.BoolPtrOutput)
}

// Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
func (o PermissionsArgsOutput) Write() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v PermissionsArgs) *bool { return v.Write }).(pulumi.BoolPtrOutput)
}

type QuotasArgs struct {
	// The maximum number of objects the bucket may hold. Unset means no limit.
	MaxObjects *int `pulumi:"maxObjects"`
	// The maximum total size, in bytes, the bucket may hold. Unset means no limit.
	MaxSize *int `pulumi:"maxSize"`
}

// QuotasArgsInput is an input type that accepts QuotasArgsArgs and QuotasArgsOutput values.
// You can construct a concrete instance of `QuotasArgsInput` via:
//
//	QuotasArgsArgs{...}
type QuotasArgsInput interface {
	pulumi.Input

	ToQuotasArgsOutput() QuotasArgsOutput
	ToQuotasArgsOutputWithContext(context.Context) QuotasArgsOutput
}

type QuotasArgsArgs struct {
	// The maximum number of objects the bucket may hold. Unset means no limit.
	MaxObjects pulumi.IntPtrInput `pulumi:"maxObjects"`
	// The maximum total size, in bytes, the bucket may hold. Unset means no limit.
	MaxSize pulumi.IntPtrInput `pulumi:"maxSize"`
}

func (QuotasArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*QuotasArgs)(nil)).Elem()
}

func (i QuotasArgsArgs) ToQuotasArgsOutput() QuotasArgsOutput {
	return i.ToQuotasArgsOutputWithContext(context.Background())
}

func (i QuotasArgsArgs) ToQuotasArgsOutputWithContext(ctx context.Context) QuotasArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(QuotasArgsOutput)
}

func (i QuotasArgsArgs) ToQuotasArgsPtrOutput() QuotasArgsPtrOutput {
	return i.ToQuotasArgsPtrOutputWithContext(context.Background())
}

func (i QuotasArgsArgs) ToQuotasArgsPtrOutputWithContext(ctx context.Context) QuotasArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(QuotasArgsOutput).ToQuotasArgsPtrOutputWithContext(ctx)
}

// QuotasArgsPtrInput is an input type that accepts QuotasArgsArgs, QuotasArgsPtr and QuotasArgsPtrOutput values.
// You can construct a concrete instance of `QuotasArgsPtrInput` via:
//
//	        QuotasArgsArgs{...}
//
//	or:
//
//	        nil
type QuotasArgsPtrInput interface {
	pulumi.Input

	ToQuotasArgsPtrOutput() QuotasArgsPtrOutput
	ToQuotasArgsPtrOutputWithContext(context.Context) QuotasArgsPtrOutput
}

type quotasArgsPtrType QuotasArgsArgs

func QuotasArgsPtr(v *QuotasArgsArgs) QuotasArgsPtrInput {
	return (*quotasArgsPtrType)(v)
}

func (*quotasArgsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**QuotasArgs)(nil)).Elem()
}

func (i *quotasArgsPtrType) ToQuotasArgsPtrOutput() QuotasArgsPtrOutput {
	return i.ToQuotasArgsPtrOutputWithContext(context.Background())
}

func (i *quotasArgsPtrType) ToQuotasArgsPtrOutputWithContext(ctx context.Context) QuotasArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(QuotasArgsPtrOutput)
}

type QuotasArgsOutput struct{ *pulumi.OutputState }

func (QuotasArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*QuotasArgs)(nil)).Elem()
}

func (o QuotasArgsOutput) ToQuotasArgsOutput() QuotasArgsOutput {
	return o
}

func (o QuotasArgsOutput) ToQuotasArgsOutputWithContext(ctx context.Context) QuotasArgsOutput {
	return o
}

func (o QuotasArgsOutput) ToQuotasArgsPtrOutput() QuotasArgsPtrOutput {
	return o.ToQuotasArgsPtrOutputWithContext(context.Background())
}

func (o QuotasArgsOutput) ToQuotasArgsPtrOutputWithContext(ctx context.Context) QuotasArgsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v QuotasArgs) *QuotasArgs {
		return &v
	}).(QuotasArgsPtrOutput)
}

// The maximum number of objects the bucket may hold. Unset means no limit.
func (o QuotasArgsOutput) MaxObjects() pulumi.IntPtrOutput {
	return o.ApplyT(func(v QuotasArgs) *int { return v.MaxObjects }).(pulumi.IntPtrOutput)
}

// The maximum total size, in bytes, the bucket may hold. Unset means no limit.
func (o QuotasArgsOutput) MaxSize() pulumi.IntPtrOutput {
	return o.ApplyT(func(v QuotasArgs) *int { return v.MaxSize }).(pulumi.IntPtrOutput)
}

type QuotasArgsPtrOutput struct{ *pulumi.OutputState }

func (QuotasArgsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**QuotasArgs)(nil)).Elem()
}

func (o QuotasArgsPtrOutput) ToQuotasArgsPtrOutput() QuotasArgsPtrOutput {
	return o
}

func (o QuotasArgsPtrOutput) ToQuotasArgsPtrOutputWithContext(ctx context.Context) QuotasArgsPtrOutput {
	return o
}

func (o QuotasArgsPtrOutput) Elem() QuotasArgsOutput {
	return o.ApplyT(func(v *QuotasArgs) QuotasArgs {
		if v != nil {
			return *v
		}
		var ret QuotasArgs
		return ret
	}).(QuotasArgsOutput)
}

// The maximum number of objects the bucket may hold. Unset means no limit.
func (o QuotasArgsPtrOutput) MaxObjects() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QuotasArgs) *int {
		if v == nil {
			return nil
		}
		return v.MaxObjects
	}).(pulumi.IntPtrOutput)
}

// The maximum total size, in bytes, the bucket may hold. Unset means no limit.
func (o QuotasArgsPtrOutput) MaxSize() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QuotasArgs) *int {
		if v == nil {
			return nil
		}
		return v.MaxSize
	}).(pulumi.IntPtrOutput)
}

type WebsiteArgs struct {
	// The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
	ErrorDocument *string `pulumi:"errorDocument"`
	// The document served for requests to the bucket root or any "directory".
	IndexDocument string `pulumi:"indexDocument"`
}

// WebsiteArgsInput is an input type that accepts WebsiteArgsArgs and WebsiteArgsOutput values.
// You can construct a concrete instance of `WebsiteArgsInput` via:
//
//	WebsiteArgsArgs{...}
type WebsiteArgsInput interface {
	pulumi.Input

	ToWebsiteArgsOutput() WebsiteArgsOutput
	ToWebsiteArgsOutputWithContext(context.Context) WebsiteArgsOutput
}

type WebsiteArgsArgs struct {
	// The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
	ErrorDocument pulumi.StringPtrInput `pulumi:"errorDocument"`
	// The document served for requests to the bucket root or any "directory".
	IndexDocument pulumi.StringInput `pulumi:"indexDocument"`
}

func (WebsiteArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WebsiteArgs)(nil)).Elem()
}

func (i WebsiteArgsArgs) ToWebsiteArgsOutput() WebsiteArgsOutput {
	return i.ToWebsiteArgsOutputWithContext(context.Background())
}

func (i WebsiteArgsArgs) ToWebsiteArgsOutputWithContext(ctx context.Context) WebsiteArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebsiteArgsOutput)
}

func (i WebsiteArgsArgs) ToWebsiteArgsPtrOutput() WebsiteArgsPtrOutput {
	return i.ToWebsiteArgsPtrOutputWithContext(context.Background())
}

func (i WebsiteArgsArgs) ToWebsiteArgsPtrOutputWithContext(ctx context.Context) WebsiteArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebsiteArgsOutput).ToWebsiteArgsPtrOutputWithContext(ctx)
}

// WebsiteArgsPtrInput is an input type that accepts WebsiteArgsArgs, WebsiteArgsPtr and WebsiteArgsPtrOutput values.
// You can construct a concrete instance of `WebsiteArgsPtrInput` via:
//
//	        WebsiteArgsArgs{...}
//
//	or:
//
//	        nil
type WebsiteArgsPtrInput interface {
	pulumi.Input

	ToWebsiteArgsPtrOutput() WebsiteArgsPtrOutput
	ToWebsiteArgsPtrOutputWithContext(context.Context) WebsiteArgsPtrOutput
}

type websiteArgsPtrType WebsiteArgsArgs

func WebsiteArgsPtr(v *WebsiteArgsArgs) WebsiteArgsPtrInput {
	return (*websiteArgsPtrType)(v)
}

func (*websiteArgsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**WebsiteArgs)(nil)).Elem()
}

func (i *websiteArgsPtrType) ToWebsiteArgsPtrOutput() WebsiteArgsPtrOutput {
	return i.ToWebsiteArgsPtrOutputWithContext(context.Background())
}

func (i *websiteArgsPtrType) ToWebsiteArgsPtrOutputWithContext(ctx context.Context) WebsiteArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebsiteArgsPtrOutput)
}

type WebsiteArgsOutput struct{ *pulumi.OutputState }

func (WebsiteArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebsiteArgs)(nil)).Elem()
}

func (o WebsiteArgsOutput) ToWebsiteArgsOutput() WebsiteArgsOutput {
	return o
}

func (o WebsiteArgsOutput) ToWebsiteArgsOutputWithContext(ctx context.Context) WebsiteArgsOutput {
	return o
}

func (o WebsiteArgsOutput) ToWebsiteArgsPtrOutput() WebsiteArgsPtrOutput {
	return o.ToWebsiteArgsPtrOutputWithContext(context.Background())
}

func (o WebsiteArgsOutput) ToWebsiteArgsPtrOutputWithContext(ctx context.Context) WebsiteArgsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v WebsiteArgs) *WebsiteArgs {
		return &v
	}).(WebsiteArgsPtrOutput)
}

// The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
func (o WebsiteArgsOutput) ErrorDocument() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WebsiteArgs) *string { return v.ErrorDocument }).(pulumi.StringPtrOutput)
}

// The document served for requests to the bucket root or any "directory".
func (o WebsiteArgsOutput) IndexDocument() pulumi.StringOutput {
	return o.ApplyT(func(v WebsiteArgs) string { return v.IndexDocument }).(pulumi.StringOutput)
}

type WebsiteArgsPtrOutput struct{ *pulumi.OutputState }

func (WebsiteArgsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebsiteArgs)(nil)).Elem()
}

func (o WebsiteArgsPtrOutput) ToWebsiteArgsPtrOutput() WebsiteArgsPtrOutput {
	return o
}

func (o WebsiteArgsPtrOutput) ToWebsiteArgsPtrOutputWithContext(ctx context.Context) WebsiteArgsPtrOutput {
	return o
}

func (o WebsiteArgsPtrOutput) Elem() WebsiteArgsOutput {
	return o.ApplyT(func(v *WebsiteArgs) WebsiteArgs {
		if v != nil {
			return *v
		}
		var ret WebsiteArgs
		return ret
	}).(WebsiteArgsOutput)
}

// The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
func (o WebsiteArgsPtrOutput) ErrorDocument() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebsiteArgs) *string {
		if v == nil {
			return nil
		}
		return v.ErrorDocument
	}).(pulumi.StringPtrOutput)
}

// The document served for requests to the bucket root or any "directory".
func (o WebsiteArgsPtrOutput) IndexDocument() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebsiteArgs) *string {
		if v == nil {
			return nil
		}
		return &v.IndexDocument
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LifecycleRuleArgsInput)(nil)).Elem(), LifecycleRuleArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*LifecycleRuleArgsArrayInput)(nil)).Elem(), LifecycleRuleArgsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PermissionsArgsInput)(nil)).Elem(), PermissionsArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*QuotasArgsInput)(nil)).Elem(), QuotasArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*QuotasArgsPtrInput)(nil)).Elem(), QuotasArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebsiteArgsInput)(nil)).Elem(), WebsiteArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebsiteArgsPtrInput)(nil)).Elem(), WebsiteArgsArgs{})
	pulumi.RegisterOutputType(LifecycleRuleArgsOutput{})
	pulumi.RegisterOutputType(LifecycleRuleArgsArrayOutput{})
	pulumi.RegisterOutputType(PermissionsArgsOutput{})
	pulumi.RegisterOutputType(QuotasArgsOutput{})
	pulumi.RegisterOutputType(QuotasArgsPtrOutput{})
	pulumi.RegisterOutputType(WebsiteArgsOutput{})
	pulumi.RegisterOutputType(WebsiteArgsPtrOutput{})
}
