// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Garage.Outputs
{

    [OutputType]
    public sealed class PermissionsArgs
    {
        /// <summary>
        /// Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
        /// </summary>
        public readonly bool? Owner;
        /// <summary>
        /// Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
        /// </summary>
        public readonly bool? Read;
        /// <summary>
        /// Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
        /// </summary>
        public readonly bool? Write;

        [OutputConstructor]
        private PermissionsArgs(
            bool? owner,

            bool? read,

            bool? write)
        {
            Owner = owner;
            Read = read;
            Write = write;
        }
    }
}
