// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PermissionsArgs {
    /**
     * @return Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
     * 
     */
    private @Nullable Boolean owner;
    /**
     * @return Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
     * 
     */
    private @Nullable Boolean read;
    /**
     * @return Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
     * 
     */
    private @Nullable Boolean write;

    private PermissionsArgs() {}
    /**
     * @return Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
     * 
     */
    public Optional<Boolean> owner() {
        return Optional.ofNullable(this.owner);
    }
    /**
     * @return Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
     * 
     */
    public Optional<Boolean> read() {
        return Optional.ofNullable(this.read);
    }
    /**
     * @return Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
     * 
     */
    public Optional<Boolean> write() {
        return Optional.ofNullable(this.write);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PermissionsArgs defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean owner;
        private @Nullable Boolean read;
        private @Nullable Boolean write;
        public Builder() {}
        public Builder(PermissionsArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.owner = defaults.owner;
    	      this.read = defaults.read;
    	      this.write = defaults.write;
        }

        @CustomType.Setter
        public Builder owner(@Nullable Boolean owner) {

            this.owner = owner;
            return this;
        }
        @CustomType.Setter
        public Builder read(@Nullable Boolean read) {

            this.read = read;
            return this;
        }
        @CustomType.Setter
        public Builder write(@Nullable Boolean write) {

            this.write = write;
            return this;
        }
        public PermissionsArgs build() {
            final var _resultValue = new PermissionsArgs();
            _resultValue.owner = owner;
            _resultValue.read = read;
            _resultValue.write = write;
            return _resultValue;
        }
    }
}
