// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class QuotasArgs {
    /**
     * @return The maximum number of objects the bucket may hold. Unset means no limit.
     * 
     */
    private @Nullable Integer maxObjects;
    /**
     * @return The maximum total size, in bytes, the bucket may hold. Unset means no limit.
     * 
     */
    private @Nullable Integer maxSize;

    private QuotasArgs() {}
    /**
     * @return The maximum number of objects the bucket may hold. Unset means no limit.
     * 
     */
    public Optional<Integer> maxObjects() {
        return Optional.ofNullable(this.maxObjects);
    }
    /**
     * @return The maximum total size, in bytes, the bucket may hold. Unset means no limit.
     * 
     */
    public Optional<Integer> maxSize() {
        return Optional.ofNullable(this.maxSize);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(QuotasArgs defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer maxObjects;
        private @Nullable Integer maxSize;
        public Builder() {}
        public Builder(QuotasArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.maxObjects = defaults.maxObjects;
    	      this.maxSize = defaults.maxSize;
        }

        @CustomType.Setter
        public Builder maxObjects(@Nullable Integer maxObjects) {

            this.maxObjects = maxObjects;
            return this;
        }
        @CustomType.Setter
        public Builder maxSize(@Nullable Integer maxSize) {

            this.maxSize = maxSize;
            return this;
        }
        public QuotasArgs build() {
            final var _resultValue = new QuotasArgs();
            _resultValue.maxObjects = maxObjects;
            _resultValue.maxSize = maxSize;
            return _resultValue;
        }
    }
}
