// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class WebsiteArgs {
    /**
     * @return The document served for requests that don&#39;t match an existing object. Defaults to Garage&#39;s built-in error page if unset.
     * 
     */
    private @Nullable String errorDocument;
    /**
     * @return The document served for requests to the bucket root or any &#34;directory&#34;.
     * 
     */
    private String indexDocument;

    private WebsiteArgs() {}
    /**
     * @return The document served for requests that don&#39;t match an existing object. Defaults to Garage&#39;s built-in error page if unset.
     * 
     */
    public Optional<String> errorDocument() {
        return Optional.ofNullable(this.errorDocument);
    }
    /**
     * @return The document served for requests to the bucket root or any &#34;directory&#34;.
     * 
     */
    public String indexDocument() {
        return this.indexDocument;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WebsiteArgs defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String errorDocument;
        private String indexDocument;
        public Builder() {}
        public Builder(WebsiteArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.errorDocument = defaults.errorDocument;
    	      this.indexDocument = defaults.indexDocument;
        }

        @CustomType.Setter
        public Builder errorDocument(@Nullable String errorDocument) {

            this.errorDocument = errorDocument;
            return this;
        }
        @CustomType.Setter
        public Builder indexDocument(String indexDocument) {
            if (indexDocument == null) {
              throw new MissingRequiredPropertyException("WebsiteArgs", "indexDocument");
            }
            this.indexDocument = indexDocument;
            return this;
        }
        public WebsiteArgs build() {
            final var _resultValue = new WebsiteArgs();
            _resultValue.errorDocument = errorDocument;
            _resultValue.indexDocument = indexDocument;
            return _resultValue;
        }
    }
}
