# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import sys
from typing import Optional

if sys.version_info >= (3, 11):
    pass
else:
    pass

itsasecret: Optional[bool]
