# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from typing import Optional

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass

import types

__config__ = pulumi.Config("provider-boilerplate")


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def itsasecret(self) -> Optional[bool]:
        return __config__.get_bool("itsasecret")
