// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.Garage
{
    [GarageResourceType("garage:index:BucketKeyPermission")]
    public partial class BucketKeyPermission : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The access key ID of the Key to grant permissions to.
        /// </summary>
        [Output("accessKeyId")]
        public Output<string> AccessKeyId { get; private set; } = null!;

        /// <summary>
        /// The ID of the Bucket to grant permissions on.
        /// </summary>
        [Output("bucketId")]
        public Output<string> BucketId { get; private set; } = null!;

        /// <summary>
        /// The read/write/owner permissions to grant.
        /// </summary>
        [Output("permissions")]
        public Output<Outputs.PermissionsArgs> Permissions { get; private set; } = null!;


        /// <summary>
        /// Create a BucketKeyPermission resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public BucketKeyPermission(string name, BucketKeyPermissionArgs args, CustomResourceOptions? options = null)
            : base("garage:index:BucketKeyPermission", name, args ?? new BucketKeyPermissionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private BucketKeyPermission(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("garage:index:BucketKeyPermission", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/axnic/pulumi-garage",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing BucketKeyPermission resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static BucketKeyPermission Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new BucketKeyPermission(name, id, options);
        }
    }

    public sealed class BucketKeyPermissionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The access key ID of the Key to grant permissions to.
        /// </summary>
        [Input("accessKeyId", required: true)]
        public Input<string> AccessKeyId { get; set; } = null!;

        /// <summary>
        /// The ID of the Bucket to grant permissions on.
        /// </summary>
        [Input("bucketId", required: true)]
        public Input<string> BucketId { get; set; } = null!;

        /// <summary>
        /// The read/write/owner permissions to grant.
        /// </summary>
        [Input("permissions", required: true)]
        public Input<Inputs.PermissionsArgsArgs> Permissions { get; set; } = null!;

        public BucketKeyPermissionArgs()
        {
        }
        public static new BucketKeyPermissionArgs Empty => new BucketKeyPermissionArgs();
    }
}
