// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.Garage
{
    [GarageResourceType("garage:index:Bucket")]
    public partial class Bucket : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The total size, in bytes, of all objects currently stored in the bucket.
        /// </summary>
        [Output("bytes")]
        public Output<int> Bytes { get; private set; } = null!;

        /// <summary>
        /// The RFC 3339 timestamp at which the bucket was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The bucket's human-readable global alias, e.g. "my-app-data". Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
        /// </summary>
        [Output("globalAlias")]
        public Output<string?> GlobalAlias { get; private set; } = null!;

        /// <summary>
        /// S3 lifecycle rules for the bucket (object expiration, incomplete-multipart-upload cleanup). Requires the provider's S3 API config (s3Endpoint/accessKeyId/secretAccessKey) to be set, and globalAlias to be set on this bucket, since lifecycle rules are managed over the S3 API, which addresses buckets by name rather than by internal ID.
        /// </summary>
        [Output("lifecycleRules")]
        public Output<ImmutableArray<Outputs.LifecycleRuleArgs>> LifecycleRules { get; private set; } = null!;

        /// <summary>
        /// The number of objects currently stored in the bucket.
        /// </summary>
        [Output("objects")]
        public Output<int> Objects { get; private set; } = null!;

        /// <summary>
        /// Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
        /// </summary>
        [Output("quotas")]
        public Output<Outputs.QuotasArgs?> Quotas { get; private set; } = null!;

        /// <summary>
        /// Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
        /// </summary>
        [Output("website")]
        public Output<Outputs.WebsiteArgs?> Website { get; private set; } = null!;


        /// <summary>
        /// Create a Bucket resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Bucket(string name, BucketArgs? args = null, CustomResourceOptions? options = null)
            : base("garage:index:Bucket", name, args ?? new BucketArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Bucket(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("garage:index:Bucket", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/axnic/pulumi-garage",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Bucket resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Bucket Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Bucket(name, id, options);
        }
    }

    public sealed class BucketArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The bucket's human-readable global alias, e.g. "my-app-data". Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
        /// </summary>
        [Input("globalAlias")]
        public Input<string>? GlobalAlias { get; set; }

        [Input("lifecycleRules")]
        private InputList<Inputs.LifecycleRuleArgsArgs>? _lifecycleRules;

        /// <summary>
        /// S3 lifecycle rules for the bucket (object expiration, incomplete-multipart-upload cleanup). Requires the provider's S3 API config (s3Endpoint/accessKeyId/secretAccessKey) to be set, and globalAlias to be set on this bucket, since lifecycle rules are managed over the S3 API, which addresses buckets by name rather than by internal ID.
        /// </summary>
        public InputList<Inputs.LifecycleRuleArgsArgs> LifecycleRules
        {
            get => _lifecycleRules ?? (_lifecycleRules = new InputList<Inputs.LifecycleRuleArgsArgs>());
            set => _lifecycleRules = value;
        }

        /// <summary>
        /// Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
        /// </summary>
        [Input("quotas")]
        public Input<Inputs.QuotasArgsArgs>? Quotas { get; set; }

        /// <summary>
        /// Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
        /// </summary>
        [Input("website")]
        public Input<Inputs.WebsiteArgsArgs>? Website { get; set; }

        public BucketArgs()
        {
        }
        public static new BucketArgs Empty => new BucketArgs();
    }
}
