// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/axnic/pulumi-garage/sdk/go/pulumi-garage/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// A bearer token authorized against the Garage Admin API. Falls back to the GARAGE_ADMIN_TOKEN environment variable if not set.
func GetAdminToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "garage:adminToken")
}

// The base URL of the Garage Admin API, e.g. "http://localhost:3903". Falls back to the GARAGE_ADMIN_ENDPOINT environment variable if not set.
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "garage:endpoint")
}
