// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PermissionsArgsArgs extends com.pulumi.resources.ResourceArgs {

    public static final PermissionsArgsArgs Empty = new PermissionsArgsArgs();

    /**
     * Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
     * 
     */
    @Import(name="owner")
    private @Nullable Output<Boolean> owner;

    /**
     * @return Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
     * 
     */
    public Optional<Output<Boolean>> owner() {
        return Optional.ofNullable(this.owner);
    }

    /**
     * Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
     * 
     */
    @Import(name="read")
    private @Nullable Output<Boolean> read;

    /**
     * @return Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
     * 
     */
    public Optional<Output<Boolean>> read() {
        return Optional.ofNullable(this.read);
    }

    /**
     * Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
     * 
     */
    @Import(name="write")
    private @Nullable Output<Boolean> write;

    /**
     * @return Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
     * 
     */
    public Optional<Output<Boolean>> write() {
        return Optional.ofNullable(this.write);
    }

    private PermissionsArgsArgs() {}

    private PermissionsArgsArgs(PermissionsArgsArgs $) {
        this.owner = $.owner;
        this.read = $.read;
        this.write = $.write;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PermissionsArgsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PermissionsArgsArgs $;

        public Builder() {
            $ = new PermissionsArgsArgs();
        }

        public Builder(PermissionsArgsArgs defaults) {
            $ = new PermissionsArgsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param owner Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
         * 
         * @return builder
         * 
         */
        public Builder owner(@Nullable Output<Boolean> owner) {
            $.owner = owner;
            return this;
        }

        /**
         * @param owner Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
         * 
         * @return builder
         * 
         */
        public Builder owner(Boolean owner) {
            return owner(Output.of(owner));
        }

        /**
         * @param read Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
         * 
         * @return builder
         * 
         */
        public Builder read(@Nullable Output<Boolean> read) {
            $.read = read;
            return this;
        }

        /**
         * @param read Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
         * 
         * @return builder
         * 
         */
        public Builder read(Boolean read) {
            return read(Output.of(read));
        }

        /**
         * @param write Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
         * 
         * @return builder
         * 
         */
        public Builder write(@Nullable Output<Boolean> write) {
            $.write = write;
            return this;
        }

        /**
         * @param write Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
         * 
         * @return builder
         * 
         */
        public Builder write(Boolean write) {
            return write(Output.of(write));
        }

        public PermissionsArgsArgs build() {
            return $;
        }
    }

}
