// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class QuotasArgsArgs extends com.pulumi.resources.ResourceArgs {

    public static final QuotasArgsArgs Empty = new QuotasArgsArgs();

    /**
     * The maximum number of objects the bucket may hold. Unset means no limit.
     * 
     */
    @Import(name="maxObjects")
    private @Nullable Output<Integer> maxObjects;

    /**
     * @return The maximum number of objects the bucket may hold. Unset means no limit.
     * 
     */
    public Optional<Output<Integer>> maxObjects() {
        return Optional.ofNullable(this.maxObjects);
    }

    /**
     * The maximum total size, in bytes, the bucket may hold. Unset means no limit.
     * 
     */
    @Import(name="maxSize")
    private @Nullable Output<Integer> maxSize;

    /**
     * @return The maximum total size, in bytes, the bucket may hold. Unset means no limit.
     * 
     */
    public Optional<Output<Integer>> maxSize() {
        return Optional.ofNullable(this.maxSize);
    }

    private QuotasArgsArgs() {}

    private QuotasArgsArgs(QuotasArgsArgs $) {
        this.maxObjects = $.maxObjects;
        this.maxSize = $.maxSize;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(QuotasArgsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private QuotasArgsArgs $;

        public Builder() {
            $ = new QuotasArgsArgs();
        }

        public Builder(QuotasArgsArgs defaults) {
            $ = new QuotasArgsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param maxObjects The maximum number of objects the bucket may hold. Unset means no limit.
         * 
         * @return builder
         * 
         */
        public Builder maxObjects(@Nullable Output<Integer> maxObjects) {
            $.maxObjects = maxObjects;
            return this;
        }

        /**
         * @param maxObjects The maximum number of objects the bucket may hold. Unset means no limit.
         * 
         * @return builder
         * 
         */
        public Builder maxObjects(Integer maxObjects) {
            return maxObjects(Output.of(maxObjects));
        }

        /**
         * @param maxSize The maximum total size, in bytes, the bucket may hold. Unset means no limit.
         * 
         * @return builder
         * 
         */
        public Builder maxSize(@Nullable Output<Integer> maxSize) {
            $.maxSize = maxSize;
            return this;
        }

        /**
         * @param maxSize The maximum total size, in bytes, the bucket may hold. Unset means no limit.
         * 
         * @return builder
         * 
         */
        public Builder maxSize(Integer maxSize) {
            return maxSize(Output.of(maxSize));
        }

        public QuotasArgsArgs build() {
            return $;
        }
    }

}
