// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.axnic.pulumi.garage.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class WebsiteArgsArgs extends com.pulumi.resources.ResourceArgs {

    public static final WebsiteArgsArgs Empty = new WebsiteArgsArgs();

    /**
     * The document served for requests that don&#39;t match an existing object. Defaults to Garage&#39;s built-in error page if unset.
     * 
     */
    @Import(name="errorDocument")
    private @Nullable Output<String> errorDocument;

    /**
     * @return The document served for requests that don&#39;t match an existing object. Defaults to Garage&#39;s built-in error page if unset.
     * 
     */
    public Optional<Output<String>> errorDocument() {
        return Optional.ofNullable(this.errorDocument);
    }

    /**
     * The document served for requests to the bucket root or any &#34;directory&#34;.
     * 
     */
    @Import(name="indexDocument", required=true)
    private Output<String> indexDocument;

    /**
     * @return The document served for requests to the bucket root or any &#34;directory&#34;.
     * 
     */
    public Output<String> indexDocument() {
        return this.indexDocument;
    }

    private WebsiteArgsArgs() {}

    private WebsiteArgsArgs(WebsiteArgsArgs $) {
        this.errorDocument = $.errorDocument;
        this.indexDocument = $.indexDocument;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(WebsiteArgsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private WebsiteArgsArgs $;

        public Builder() {
            $ = new WebsiteArgsArgs();
        }

        public Builder(WebsiteArgsArgs defaults) {
            $ = new WebsiteArgsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param errorDocument The document served for requests that don&#39;t match an existing object. Defaults to Garage&#39;s built-in error page if unset.
         * 
         * @return builder
         * 
         */
        public Builder errorDocument(@Nullable Output<String> errorDocument) {
            $.errorDocument = errorDocument;
            return this;
        }

        /**
         * @param errorDocument The document served for requests that don&#39;t match an existing object. Defaults to Garage&#39;s built-in error page if unset.
         * 
         * @return builder
         * 
         */
        public Builder errorDocument(String errorDocument) {
            return errorDocument(Output.of(errorDocument));
        }

        /**
         * @param indexDocument The document served for requests to the bucket root or any &#34;directory&#34;.
         * 
         * @return builder
         * 
         */
        public Builder indexDocument(Output<String> indexDocument) {
            $.indexDocument = indexDocument;
            return this;
        }

        /**
         * @param indexDocument The document served for requests to the bucket root or any &#34;directory&#34;.
         * 
         * @return builder
         * 
         */
        public Builder indexDocument(String indexDocument) {
            return indexDocument(Output.of(indexDocument));
        }

        public WebsiteArgsArgs build() {
            if ($.indexDocument == null) {
                throw new MissingRequiredPropertyException("WebsiteArgsArgs", "indexDocument");
            }
            return $;
        }
    }

}
