// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface PermissionsArgsArgs {
    /**
     * Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
     */
    owner?: pulumi.Input<boolean>;
    /**
     * Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
     */
    read?: pulumi.Input<boolean>;
    /**
     * Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
     */
    write?: pulumi.Input<boolean>;
}

export interface QuotasArgsArgs {
    /**
     * The maximum number of objects the bucket may hold. Unset means no limit.
     */
    maxObjects?: pulumi.Input<number>;
    /**
     * The maximum total size, in bytes, the bucket may hold. Unset means no limit.
     */
    maxSize?: pulumi.Input<number>;
}

export interface WebsiteArgsArgs {
    /**
     * The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
     */
    errorDocument?: pulumi.Input<string>;
    /**
     * The document served for requests to the bucket root or any "directory".
     */
    indexDocument: pulumi.Input<string>;
}
