// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Garage.Inputs
{

    public sealed class PermissionsArgsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the key has owner rights on the bucket (manage bucket-level settings such as its website configuration or quotas via the S3 API).
        /// </summary>
        [Input("owner")]
        public Input<bool>? Owner { get; set; }

        /// <summary>
        /// Whether the key can read objects (GetObject, ListObjects, ...) from the bucket.
        /// </summary>
        [Input("read")]
        public Input<bool>? Read { get; set; }

        /// <summary>
        /// Whether the key can write objects (PutObject, DeleteObject, ...) to the bucket.
        /// </summary>
        [Input("write")]
        public Input<bool>? Write { get; set; }

        public PermissionsArgsArgs()
        {
        }
        public static new PermissionsArgsArgs Empty => new PermissionsArgsArgs();
    }
}
