// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.Garage.Inputs
{

    public sealed class LifecycleRuleArgsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Abort incomplete multipart uploads this many days after they were initiated. Omit to not clean these up automatically.
        /// </summary>
        [Input("abortIncompleteMultipartUploadDays")]
        public Input<int>? AbortIncompleteMultipartUploadDays { get; set; }

        /// <summary>
        /// Whether this rule is active.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// Delete objects this many days after creation. Omit to not expire objects by age.
        /// </summary>
        [Input("expirationDays")]
        public Input<int>? ExpirationDays { get; set; }

        /// <summary>
        /// A unique identifier for this rule within the bucket.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Only objects whose key starts with this prefix are affected. Omit to match every object in the bucket.
        /// </summary>
        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        public LifecycleRuleArgsArgs()
        {
        }
        public static new LifecycleRuleArgsArgs Empty => new LifecycleRuleArgsArgs();
    }
}
