// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.Garage.Inputs
{

    public sealed class QuotasArgsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The maximum number of objects the bucket may hold. Unset means no limit.
        /// </summary>
        [Input("maxObjects")]
        public Input<int>? MaxObjects { get; set; }

        /// <summary>
        /// The maximum total size, in bytes, the bucket may hold. Unset means no limit.
        /// </summary>
        [Input("maxSize")]
        public Input<int>? MaxSize { get; set; }

        public QuotasArgsArgs()
        {
        }
        public static new QuotasArgsArgs Empty => new QuotasArgsArgs();
    }
}
