// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.Garage.Inputs
{

    public sealed class WebsiteArgsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The document served for requests that don't match an existing object. Defaults to Garage's built-in error page if unset.
        /// </summary>
        [Input("errorDocument")]
        public Input<string>? ErrorDocument { get; set; }

        /// <summary>
        /// The document served for requests to the bucket root or any "directory".
        /// </summary>
        [Input("indexDocument", required: true)]
        public Input<string> IndexDocument { get; set; } = null!;

        public WebsiteArgsArgs()
        {
        }
        public static new WebsiteArgsArgs Empty => new WebsiteArgsArgs();
    }
}
