// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Bucket extends pulumi.CustomResource {
    /**
     * Get an existing Bucket resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Bucket {
        return new Bucket(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'garage:index:Bucket';

    /**
     * Returns true if the given object is an instance of Bucket.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bucket {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bucket.__pulumiType;
    }

    /**
     * The total size, in bytes, of all objects currently stored in the bucket.
     */
    declare public /*out*/ readonly bytes: pulumi.Output<number>;
    /**
     * The RFC 3339 timestamp at which the bucket was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The bucket's human-readable global alias, e.g. "my-app-data". Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
     */
    declare public readonly globalAlias: pulumi.Output<string | undefined>;
    /**
     * The number of objects currently stored in the bucket.
     */
    declare public /*out*/ readonly objects: pulumi.Output<number>;
    /**
     * Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
     */
    declare public readonly quotas: pulumi.Output<outputs.QuotasArgs | undefined>;
    /**
     * Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
     */
    declare public readonly website: pulumi.Output<outputs.WebsiteArgs | undefined>;

    /**
     * Create a Bucket resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: BucketArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["globalAlias"] = args?.globalAlias;
            resourceInputs["quotas"] = args?.quotas;
            resourceInputs["website"] = args?.website;
            resourceInputs["bytes"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["objects"] = undefined /*out*/;
        } else {
            resourceInputs["bytes"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["globalAlias"] = undefined /*out*/;
            resourceInputs["objects"] = undefined /*out*/;
            resourceInputs["quotas"] = undefined /*out*/;
            resourceInputs["website"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Bucket.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Bucket resource.
 */
export interface BucketArgs {
    /**
     * The bucket's human-readable global alias, e.g. "my-app-data". Buckets can be created without one and addressed only by ID, but an alias is required to use the bucket over the S3 API with most clients. Only a single global alias is supported; local (per-key) aliases and multiple global aliases are not managed by this provider.
     */
    globalAlias?: pulumi.Input<string>;
    /**
     * Storage quotas for the bucket. Omit either field, or the whole block, to leave that limit unset.
     */
    quotas?: pulumi.Input<inputs.QuotasArgsArgs>;
    /**
     * Static-website hosting configuration for the bucket. Omit to leave website hosting disabled.
     */
    website?: pulumi.Input<inputs.WebsiteArgsArgs>;
}
