// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class BucketKeyPermission extends pulumi.CustomResource {
    /**
     * Get an existing BucketKeyPermission resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): BucketKeyPermission {
        return new BucketKeyPermission(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'garage:index:BucketKeyPermission';

    /**
     * Returns true if the given object is an instance of BucketKeyPermission.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BucketKeyPermission {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BucketKeyPermission.__pulumiType;
    }

    /**
     * The access key ID of the Key to grant permissions to.
     */
    declare public readonly accessKeyId: pulumi.Output<string>;
    /**
     * The ID of the Bucket to grant permissions on.
     */
    declare public readonly bucketId: pulumi.Output<string>;
    /**
     * The read/write/owner permissions to grant.
     */
    declare public readonly permissions: pulumi.Output<outputs.PermissionsArgs>;

    /**
     * Create a BucketKeyPermission resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BucketKeyPermissionArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.accessKeyId === undefined && !opts.urn) {
                throw new Error("Missing required property 'accessKeyId'");
            }
            if (args?.bucketId === undefined && !opts.urn) {
                throw new Error("Missing required property 'bucketId'");
            }
            if (args?.permissions === undefined && !opts.urn) {
                throw new Error("Missing required property 'permissions'");
            }
            resourceInputs["accessKeyId"] = args?.accessKeyId;
            resourceInputs["bucketId"] = args?.bucketId;
            resourceInputs["permissions"] = args?.permissions;
        } else {
            resourceInputs["accessKeyId"] = undefined /*out*/;
            resourceInputs["bucketId"] = undefined /*out*/;
            resourceInputs["permissions"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BucketKeyPermission.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a BucketKeyPermission resource.
 */
export interface BucketKeyPermissionArgs {
    /**
     * The access key ID of the Key to grant permissions to.
     */
    accessKeyId: pulumi.Input<string>;
    /**
     * The ID of the Bucket to grant permissions on.
     */
    bucketId: pulumi.Input<string>;
    /**
     * The read/write/owner permissions to grant.
     */
    permissions: pulumi.Input<inputs.PermissionsArgsArgs>;
}
